#!/usr/bin/env bash
set -e

if [ ! -z "$1" ]; then
  if [[ "$1" == "--me" || "$1" == "-me" ]]; then
    if [[ $(tput lines) > 35 ]]; then
      preview_height=30
    elif [[ $(tput lines) > 25 ]]; then
      preview_height=20
    else
      preview_height=0
    fi

    GH_FORCE_TTY='100%' gh pr list --assignee @me --limit 100 |
      tail -n +4 |
      fzf --ansi \
      --preview-window down:$preview_height \
        --bind ctrl-d:preview-down \
        --bind ctrl-u:preview-up \
        --preview 'GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh pr view {1} | bat -p --color always -l md' |
      awk '{print $1}' |
      tr -d '#' |
      xargs -I {} gh pr view {} --json headRefName |
      jq -r '.headRefName' |
      xargs -I {} git checkout {}
  fi
  exit 0
fi


branch=$(git branch -a | fzf | tr -d ' ')

if [ ! -z "$branch" ]; then
  if [[ "$branch" == *"remotes/"* ]]; then
    b=$(echo "$branch" | awk -F'/' '{print $3}')
    git checkout -b "$b" "$branch"
  else
    git checkout "$branch"
  fi
fi
